# Generated by Django 5.2 on 2025-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittlelemonAPI", "0002_create_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="inventory",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
