# Generated by Django 5.2 on 2025-05-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittlelemonAPI", "0003_alter_menuitem_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
